#===========================#
#=*= Topics and Keywords =*=#
#===========================#

# Based on Gentzkow et al.s' keyword list


subject_keywords = {
 'abortion': ['abortion',
<<<<<<< HEAD
              'unborn',
              'fetus',
              'pro life',
              'pro choice',
              'right to choose',
              'right choose',
              'roe v wade',
              'roe wade',
              'sanctity of life',
              'sanctity life',
              'family plan'
             ],
 'alcohol': ['alcohol',
             'antisaloon',
             'liquor',
             'saloon'
            ],
 'budget': ['budget',
            'budget deficit',
            'national debt',
            'nations debt'
           ],
 'business': ['bankrupt',
              'busi',
              'sba',
              'corporat'
             ],
 'crime': ['crime',
           'crimin',
           'prison'
          ],
=======
#               'unborn',
              'fetus',
              'pro life',
              'pro choice',
#               'right to choose',
#               'right choose',
              'roe v wade',
              'roe vs wade',
              'roe wade',
              'family plan'
             ],
 'drug_alcohol': ['alcohol',
                  'antisaloon',
                  'liquor',
                  'saloon',
                  'drug',
                  'marajuana'
                  ],
 'budget': ['budget',
            'budget deficit',
            'national debt',
            'nations debt',
            '\bcbo\b'
           ],
#  'business': ['bankrupt',
#               'busi',
#               'sba',
#               'corporat'
#              ],
#  'crime': ['crime',
#            'crimin',
#            'prison'
#           ],
>>>>>>> reese
 'guns': ['gun',
          'firearm',
          'assault weapon',
          'assault rifle'
<<<<<<< HEAD
          'nra',
          'rifle',
          'second amendment'
         ],   # nothing should preceed this
 'drugs': ['drug',
           'narcot',
           'heroin',
           'opium',
           'marajuana',
           'crack',
           'meth'
          ],
=======
          '\bnra\b',
          'rifle',
          'second amendment'
         ],   # nothing should preceed this
#  'drugs': ['drug',
#            'narcot',
#            'heroin',
#            'opium',
#            'marajuana',
#            'crack',
#           ],
>>>>>>> reese
 'defense': ['army',
             'atom',
             'arms',
             'bomb',
             'combat',
             'defens',
             'enlist',
             'fighter',
             'guard',
             'homeland',
             'intellig',
             'militar',
             'missil',
             'naval',
             'navy',
             'navyyard',
             'prison',
             'soldier',
             'torpedo',
             'veteran',
             'war',
             'weapon',
#              'force',
#              'aof',
#              'oef',
             'operation eduring freedom',
#              'oif',
             'operation iraqi freedom',
             'arms appropriation'
<<<<<<< HEAD
             'troop'
=======
             'troop',
             'coast guard'
>>>>>>> reese
            ],
 'economy': ['econom',
             'povert',
             'unemploy',
             'gdp',
             'gross domestic product',
             'market'
            ],
 'education': ['academ',
               'campus',
               'educat',
               'lunch',
               'school',
               'student',
               'teacher',
               'college'
              ],
<<<<<<< HEAD
 'elections': ['ballot',
               'elect'
              ],  # nothing should preceed this or space
 'environment': ['canyon',
                 'climat',
                 'climate change',
                 'environmental',
                 'the environment',
                 'forest',
                 'pollut',
                 'drought'
                ],
 'federalism': ['confeder',
                'interst',
                'government regul',
                'small gov',
                'big gov',
                'secede'
               ],
=======
#  'elections': ['ballot',
#                'elect'
#               ],  # nothing should preceed this or space
#  'environment': ['canyon',
#                  'climat',
#                  'climate change',
#                  'environmental',
#                  'the environment',
#                  'forest',
#                  'pollut',
#                  'drought',
#                  'contamination'
#                 ],
#  'federalism': ['confeder',
#                 'interst',
#                 'government regul',
#                 'small gov',
#                 'big gov',
#                 'secede'
#                ],
>>>>>>> reese
 'foreign': ['afghanistan',
             'aid',
             'asia',
             'bolivia',
             'britain',
             'canada',
             'china',
             'chines',
             'cold war',
             'communism',
             'communist',
             'contra',
             'cuba',
             'duti',
             'foreign',
             'genocid',
             'german',
             'haiti',
             'independ',
             'iran',
             'iraq',
             'khmer',
             'kingdom',
             'latin',
             'mexic',
             'nicaragua',
             'panama',
             'persia',
             'phillipin',
             'porto',
             'postcold war',
             'puerto',
             'qaeda',
             'saddam hussein',
             'salvador',
             'soviet',
             'spain',
             'spanish',
             'spanishamerican',
             'treaty',
             'troop',
             'vietnam'
            ],
<<<<<<< HEAD
 'government': ['entitlement',
                'bureau',
                'depart',
                'govern',
                'highway',
                'lineitem',
                'medicaid',
                'medicar',
                'municip',
                'privacy',
                'regulator',
                'stimulus',
                'welfare'
               ],
=======
#  'government': ['entitlement',
#                 'bureau',
#                 'depart',
#                 'govern',
#                 'highway',
#                 'lineitem',
#                 'medicaid',
#                 'medicar',
#                 'municip',
#                 'privacy',
#                 'regulator',
#                 'stimulus',
#                 'welfare'
#                ],
>>>>>>> reese
 'health': ['care reform',
            'health care',
            'healthcare',
            'health plan',
            'health coverag',
            'health insur',
            'insurance coverag',
            'uninsured',
<<<<<<< HEAD
            'hiv',
=======
            '\bhiv\b',
>>>>>>> reese
            'medical',
            'medicaid',
            'medicar',
#             'aca',
            'affordable care',
            'patient protection'
<<<<<<< HEAD
           ],
 'immigration': ['alien',
                'border',
                'immigration',
=======
            'doctor'
           ],
 'immigration': ['alien',
#                 'border',
                'immigrat',
>>>>>>> reese
                'undocumented',
                'refugee',
                'migrant'
                ],
<<<<<<< HEAD
 'justice': ['attorney',
             'clerk',
             'court',
             'freedman',
             'habeaius',
             'judicial',
             'justic',
             'lawyer',
             'trial'
            ],
=======
#  'justice': ['attorney',
#              'clerk',
#              'court',
#              'freedman',
#              'habeaius',
#              'judicial',
#              'justic',
#              'lawyer',
#              'trial'
#             ],
>>>>>>> reese
 'labor': ['employment',
#            'job',
           'labor',
           'longshoremen',
           'pension',
           'retire',
           'salary',
           'strike',
           'unemploy',
           'union',
           'vocation',
           'wage',
           'worker'
          ],
<<<<<<< HEAD
 'mail': ['freedeliver',
          'mail',
          'messeng',
          'postal',
          'postmaster',
          'postoffice'
         ],
=======
#  'mail': ['freedeliver',
#           'mail',
#           'messeng',
#           'postal',
#           'postmaster',
#           'postoffice'
#          ],
>>>>>>> reese
 'minorities': ['minorities',
                'people color',
                'people of color',
                'colored people',
                'african american',
                'mexican american',
                'asian american',
                'hispanic american',
                'africanamerican',
                'mexicanamerican',
                'asianamerican',
                'hispanicamerican',
                'cheroke',
                'choctaw',
                'filipino',
                'hawaiian',
                'indian',
                'jew',
                'muslim',
                'negro',
                'philippin',
                'rights act',
                'segreg',
                'tribal',
                'tribe',
                'racebased',
                'raceneutral',
                'racial',
               ],
 'women':['misogyny',
          'sexi',
          'femin',
          'contraceptive',
          'planned parenthood',
          'equal pay',
          'domestic violence',
<<<<<<< HEAD
          'gender'
         ],
 'money': ['cash',
           'coin',
           'dollar',
           'gold',
           'monetary',
           'silver',
           'tender',
           'treasur'
           'benchmark rate'
          ],
 'religion': ['buddhi',
              'catholic',
              'christian',
              'hindu',
              'islam',
              'jehovah',
              'jew',
              'judaism',
              'mormon',
              'muslim',
              'religion'
             ],
=======
          'gender',
          'rape',
          'sexual assault'
         ],
#  'money': ['cash',
#            'coin',
#            'currency',
#            'dollar',
#            'gold',
#            'monetary',
#            'silver',
#            'tender',
#            'treasur'
#            'benchmark rate'
#           ],
#  'religion': ['buddhi',
#               'catholic',
#               'christian',
#               'hindu',
#               'islam',
#               'jehovah',
#               'jew',
#               'judaism',
#               'mormon',
#               'muslim',
#               'religion'
#              ],
>>>>>>> reese
 'tax': ['estate',
         'excessprofit',
         'internalrevenue',
         'tax',
         'tarrif',
         'capital gains',
<<<<<<< HEAD
         'income',
         'corporat'
=======
         'income tax',
#          'corporat'
>>>>>>> reese
        ],
 'trade': ['export',
           'imports',
           'payne aldrich',
           'tariff',
           'trade',
           'valorem',
           'nafta',
           'n.a.f.t.a',
           'north american free trade agreement',
           'tpp',
           'transpacific partnership'
          ]}



# Original subject keywords from Gentzkow et al.


# KEYWORDS = "phrase_clusters/keywords.txt"
# keywords = (pd.read_csv(os.path.join(DATA_PATH, KEYWORDS), sep = "|")
#            .groupby("topic")["phrase"]
#            .apply(list)
#            .to_dict())


original_subject_keywords = {
 'alcohol': ['alcohol',
  'antisaloon',
  'distil',
  'liquor',
  'malt',
  'saloon',
  'spirit'],
 'budget': ['balanc',
  'budget',
  'debt',
  'defici',
  'expenditur',
  'expens',
  'revenu',
  'spend',
  'treasuri'],
 'business': ['agricultur',
  'banker',
  'bankruptci',
  'busi',
  'canal',
  'capit',
  'chief execut',
  'coal',
  'commerc',
  'commod',
  'compani',
  'credit',
  'electr',
  'enterpri',
  'farm',
  'financ',
  'fishermen',
  'gas',
  'industri',
  'leather',
  'loan',
  'manufactur',
  'mine',
  'oil',
  'owner',
  'patent',
  'petroleum',
  'plant',
  'potato',
  'privat',
  'profit',
  'railroad',
  'refin',
  'salt',
  'stock',
  'sugar',
  'textil',
  'wool'],
 'crime': ['crim',
  'crime',
  'drug',
  'gun',
  'narcot',
  'opium',
  'prison',
  'rehabilit',
  'sentenc',
  'shoot',
  'traffick'],
 'defense': ['arm',
  'armi',
  'atom',
  'bomb',
  'combat',
  'defens',
  'enlist',
  'fighter',
  'guard',
  'homeland',
  'intellig',
  'militari',
  'missil',
  'naval',
  'navi',
  'navyyard',
  'prison',
  'soldier',
  'torpedo',
  'veteran',
  'war',
  'weapon'],
 'economy': ['econom',
  'growth',
  'poverti',
  'recoveri',
  'stimulus',
  'unemploy'],
 'education': ['academ',
  'campus',
  'educ',
  'lunch',
  'school',
  'student',
  'teacher'],
 'elections': ['ballot', 'campaign', 'elect', 'vote'],
 'environment': ['canyon',
  'climat',
  'conserv',
  'contam',
  'dam',
  'environ',
  'eros',
  'forest',
  'garden',
  'hurrican',
  'lake',
  'natur',
  'plant',
  'pollut',
  'shale',
  'soil',
  'wast'],
 'federalism': ['agenc',
  'confeder',
  'execut',
  'feder',
  'interst',
  'local',
  'regul',
  'secede',
  'southern',
  'state',
  'union'],
 'foreign': ['afghanistan',
  'aid',
  'asia',
  'bolivia',
  'britain',
  'canada',
  'china',
  'chines',
  'cold war',
  'communism',
  'communist',
  'contra',
  'cuba',
  'duti',
  'foreign',
  'genocid',
  'german',
  'haiti',
  'independ',
  'iran',
  'iraq',
  'khmer',
  'kingdom',
  'latin',
  'mexic',
  'nicaragua',
  'panama',
  'persia',
  'phillipin',
  'porto',
  'postcold war',
  'puerto',
  'qaeda',
  'saddam hussein',
  'salvador',
  'soviet',
  'spain',
  'spanish',
  'spanishamerican',
  'treati',
  'troop',
  'vietnam'],
 'government': ['agenc',
  'benefit',
  'bureau',
  'depart',
  'govern',
  'highway',
  'lineitem',
  'medicaid',
  'medicar',
  'municip',
  'privaci',
  'regulatori',
  'stimulus',
  'welfar'],
 'health': ['care',
  'care reform',
  'cell',
  'coverag',
  'gyn',
  'health',
  'hiv',
  'hospit',
  'medic',
  'medicaid',
  'medicar',
  'mental',
  'nurs',
  'nutrit'],
 'immigration': ['alien',
  'border',
  'citizen',
  'detain',
  'foreign',
  'illeg',
  'immigr',
  'undoc'],
 'justice': ['attorney',
  'clerk',
  'court',
  'freedman',
  'habea',
  'judici',
  'justic',
  'lawyer',
  'right',
  'trial'],
 'labor': ['compens',
  'employ',
  'job',
  'labor',
  'longshoremen',
  'pay',
  'pension',
  'retir',
  'salari',
  'strike',
  'unemploy',
  'union',
  'vocat',
  'wage',
  'worker'],
 'mail': ['freedeliveri', 'mail', 'messeng', 'posta', 'postmast', 'postoffic'],
 'minorities': ['african',
  'cheroke',
  'choctaw',
  'color',
  'discrimin',
  'equal',
  'filipino',
  'hate',
  'hawaiian',
  'indian',
  'jew',
  'muslim',
  'negro',
  'philippin',
  'right',
  'right act',
  'segreg',
  'tribal',
  'tribe',
  'woman',
  'women'],
 'money': ['cash',
  'coin',
  'dollar',
  'gold',
  'monet',
  'note',
  'payment',
  'silver',
  'tender',
  'treasuri'],
 'religion': ['buddhi',
  'cathol',
  'christian',
  'hindu',
  'islam',
  'jehovah',
  'jew',
  'judai',
  'mormon',
  'muslim',
  'prayer',
  'protest',
  'religi',
  'sectarian'],
 'tax': ['estat', 'excessprofit', 'internalrevenu', 'tax'],
 'trade': ['duti',
  'exportimport',
  'paynealdrich',
  'tariff',
  'trade',
  'valorem']}
